### ISSUE TITLE
[Feature Request] Unique writes only

### ISSUE THREAD

**Issue by CactusProjects** [smitty10010/adsb_scripts#1]
Hi, hope you don't mind requesting a feature, I have this in use and really impressed. (I've never worked with databases) Do you think this could be updated to only make an entry in the database if the date, hex unique combination does not exist already? Basically I just want loq unique flights overhead per day. (or perhaps not more than one entry per hex identifier lets say every hour as could land and take off so might be a couple of genuine passes per day.)

I had a go off this: https://stackoverflow.com/questions/15115264/sqlite-upsert-with-2-constraints but just don't know enough to make it work.

**Comment by smitty10010** [comment]
Sure I can make that change.

**Comment by smitty10010** [comment]
Okay, I made the requested changes. Now it will only log the same aircraft if it is more than an hour old from the last record in the database. Give it a try and let me know what you think.

**Comment by CactusProjects** [comment]
Awesome, checking it out right now! Thanks

**Comment by CactusProjects** [comment]
I have have it up and running, thanks for the work, didn't realise there would be that much new code! Just FYI if there is no planes at all with latitude data present it throws an error here. I record all so doesn't bother me. Will put in a try/catch if I use it.
`#df1.dropna(subset=['lat'], inplace=True)
`

Finally I use SQLite so I had to change the read line to:
`df2 = pd.read_sql("SELECT * FROM flight_data WHERE flight_data.date_time > datetime('now', '-3600 seconds')", engine)
`

Thanks!

**Comment by smitty10010** [comment]
Oh cool. Yeah you can just comment out that section where I remove any rows that don't contain locational data. I'll probably do some more cleanup on the code since I'm using nested loops and instead should use map reduce functions for efficiency. This was fun, let me know if you have anymore ideas. I'm thinking of doing a dash board of the aircraft activity around me.

**Comment by CactusProjects** [comment]
Wondering if you are getting any duplicates in your DB? For me it duplicates if the hex field is decimal only but doesn't duplicate if any non-numeric in the hex field. Should be something I can track down myself in a day or two. My plan is to have a webpage that shows all the flights of the day which is really straightforward. For something like the activity check out tar1090 or timelape1090 which may do some/all of what you are looking for. I think the last 'idea' I have which probably complicates everything is that when we now write once per hex value sometime the flight name isn't present in that particular data packet, be nice to insert it if it became available but it does the job just fine now!

**Comment by smitty10010** [comment]
I have duplicates but only if they are separated by an hour or more in time. I don't seem to have duplicates within the same hour.
